server:
  port: 8080
  error:
    include-message: always
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,loggers"
      base-path: /manage

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      auto-index-creation: true
      uri: ${mongodb.uri}

    web:
      pageable:
        size-parameter: page-size
        page-parameter: page
        default-page-size: 50
        one-indexed-parameters: false
        max-page-size: 1000

processor:
  enabled: true

  # Async config for the processor threads
  thread-pool:
    initial-size: 10
    max-size: 30

  # How often to check for new queue records if the queue is empty
  query-frequency: 10s

  # If false, then queue records will be set to COMPLETE instead of deleted (useful for testing)
  delete-on-complete: true

service-output-expiration: 10d

---

spring:
  config:
    activate:
      on-profile: nonprod

envType: NONPROD
---

spring:
  config:
    activate:
      on-profile: sandbox

server:
  port: 8180

logging:
  level:
    org.cdsframework.rckms: TRACE

mongodb:
  #uri: mongodb://localhost:8888/ss-comparison-service?maxIdleTimeMS=300000
  #uri: mongodb://localhost:27017/ss-comparison-service?maxIdleTimeMS=300000
  uri: mongodb://blake:0tQ34vRq8y-@docdb-2021-05-04-18-29-11.cluster-c8xky1n7ytea.us-east-1.docdb.amazonaws.com:27017/ss-comparison-service?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

management-base-url: http://localhost:8180/ss-comparison-service/v1/management
