server:
  port: 8080
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,loggers"
      base-path: /manage

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      auto-index-creation: true
      uri: ${mongodb.uri}

    web:
      pageable:
        size-parameter: page-size
        page-parameter: page
        default-page-size: 50
        one-indexed-parameters: false
        max-page-size: 1000

processor:
  enabled: true

  # Async config for the processor threads
  thread-pool:
    initial-size: 10
    max-size: 30

  # How often to check for new queue records if the queue is empty
  query-frequency: 10s

  # If false, then queue records will be set to COMPLETE instead of deleted (useful for testing)
  delete-on-complete: true

---

spring:
  config:
    activate:
      on-profile: sandbox

server:
  port: 8180

logging:
  level:
    org.cdsframework.rckms: TRACE

mongodb:
  uri: mongodb://localhost:8888/ss-comparison-service?maxIdleTimeMS=300000
